<a href="https://colab.research.google.com/github/swethaelangovan518/calculator/blob/main/Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#create a list
fruits=['apple','banana','mango']
print(fruits)

['apple', 'banana', 'mango']


In [5]:
#append
fruits.append("orange")
print(fruits)

['apple', 'banana', 'mango', 'orange', 'orange']


In [7]:
#extend
fruits.extend(["pineapple","grapes"])
print(fruits)

['apple', 'banana', 'mango', 'orange', 'orange', 'pineapple', 'grapes']


In [9]:
#Remove
fruits.remove("apple")
print(fruits)

['banana', 'mango', 'orange', 'orange', 'pineapple', 'grapes']


In [10]:
#removes last element and written it
last_item=fruits.pop()
print(last_item)

grapes


In [11]:
#returns the index of the value
pos=fruits.index("banana")
print(pos)

0


In [12]:
#find the position of the item
pos=fruits.index("mango")
print(pos)

1


In [13]:
#Slicing (get the postion od the list)
print(fruits[1:3])

['mango', 'orange']


In [14]:
#sort (Arrange in asscending order)
num=[5,4,6,8,2]
num.sort()
print(num)

[2, 4, 5, 6, 8]


In [15]:
#Reverse
num.reverse()
print(num)

[8, 6, 5, 4, 2]


In [16]:
#length
print(len(fruits))


5


In [17]:
#Sum(only if the list contains list)
scores=[80,50,60]
total=sum(scores)
print(total)

190


In [18]:
# list comprehension
squares=[x**2 for x in range(1,6)]
print(squares)

[1, 4, 9, 16, 25]


In [19]:
#Integer
students_in_class=45
print("Total stuudents:",students_in_class)

Total stuudents: 45


In [20]:
#Float
product=245.566
discount=0.1
final_price=product*(1-discount)
print("Final price:",final_price)

Final price: 221.0094


In [21]:
#Complex
impedancee=4+5j
print("Impedance:",impedancee)

Impedance: (4+5j)


In [22]:
#Text type(string)
username="alex234"
welcome_msg=f"Welcome,{username}!"
print(welcome_msg)

Welcome,alex234!


In [26]:
#Boolean
marks=78
is_passed=marks>50
print("Is passed:",is_passed)

Is passed: True


In [27]:
#Sequence Type
cart_items=["apple","banana","orange"]
print("Cart items:",cart_items)

Cart items: ['apple', 'banana', 'orange']


In [28]:
#Location
location=(40.7128,-74.0060)
print("Location:",location)

Location: (40.7128, -74.006)


In [29]:
#Range
for roll_no in range(1,11):
    print("Roll number:",roll_no)

Roll number: 1
Roll number: 2
Roll number: 3
Roll number: 4
Roll number: 5
Roll number: 6
Roll number: 7
Roll number: 8
Roll number: 9
Roll number: 10


In [33]:
#Mapping
employee={"id":101,"name":"John","salary":50000}
print(f"{employee['name']} earns {employee['salary']} per month and her id is {employee['id']}")

John earns 50000 per month and her id is 101


In [34]:
#set type
language={"Python","Java","Python","C++"}
print("Language:",language)

Language: {'Java', 'Python', 'C++'}


In [36]:
#Frozen list
vowels=frozenset(['a','e','i','o','u'])
print("Vowels(unchanged):",vowels)

Vowels(unchanged): frozenset({'e', 'u', 'o', 'a', 'i'})


In [37]:
#creating one dimensional array

import numpy as np
marks=np.array([34,56,78,90,67,99])
print("Marks:",marks)

Marks: [34 56 78 90 67 99]


In [39]:
#Creating two dimensional array

matrix=np.array([[2,3],[4,5]])
print("Matrix:\n",matrix)

Matrix:
 [[2 3]
 [4 5]]


In [41]:
#Accesing elements

print(marks[1])
print(matrix[1,0])

56
4


In [42]:
#Array properties

print("Shape:\n",matrix.shape)
print("Size:",matrix.size)
print("Data type:",matrix.dtype)
print("Dimension:\n",matrix)

Shape:
 (2, 2)
Size: 4
Data type: int64
Dimension:
 [[2 3]
 [4 5]]


In [45]:
#Indexing\slicing
import numpy as np
matrix=np.array([[2,3],[3,6]])
print(matrix[1,1])
print(matrix[:1])

6
[[2 3]]


In [54]:
# Array of zeros ,ones and range

zeros=np.zeros((2,3))
ones=np.ones((2,4))
range_array=np.arange(1,10,2)
print("Zeros:\n",zeros)
print("Ones:\n",ones)
print("Range:\n",range_array)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range:
 [1 3 5 7 9]


In [55]:
#Reshape an array

arr=np.array([1,2,3,4,5,6])
reshaped_arr=arr.reshape(2,3)
print("Reshaped array:\n",reshaped_arr)

Reshaped array:
 [[1 2 3]
 [4 5 6]]


In [57]:
eye=np.eye(3)
linespace=np.linspace(0,1,5)
print("Identity matrix:\n",eye)
print("Linespace:\n",linespace)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Linespace:
 [0.   0.25 0.5  0.75 1.  ]


In [59]:
#creating three dimensional array

import numpy as np
arr3d=np.array([[[1,2,3],[3,4,5]],[[4,5,6],[4,6,7]]])
print("3D array:\n",arr3d)

3D array:
 [[[1 2 3]
  [3 4 5]]

 [[4 5 6]
  [4 6 7]]]


In [60]:
#Computstiona on Numpy Array

# 1. Arithmetic operation

import numpy as np
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a+b)
print(a-b)
print(a/b)
print(a*b)

[11 22 33]
[ 9 18 27]
[10. 10. 10.]
[10 40 90]


In [61]:

# 2. Scalar Operations

print(a*2)
print(a+2)


[20 40 60]
[12 22 32]


In [65]:
# 3. Matrix multiplutation

A=np.array([[1,2],[3,4]])
B=np.array([[4,5],[4,7]])
print(A)
print("\n",B)


# Element wise multiplution


# print(A*B)

print(np.dot(A,B))

print(A@B)


[[1 2]
 [3 4]]

 [[4 5]
 [4 7]]
[[12 19]
 [28 43]]
[[12 19]
 [28 43]]


In [66]:
# comparison operation

print(a>15)
print(a==20)

[False  True  True]
[False  True False]


In [68]:
# 1. Mathematical Functions(Element wise)

import numpy as np

a=np.array([1,2,3,4,5,6])
print("exp:",np.exp(a))
print("sqrt:",np.sqrt(a))
print("sin:",np.sin(a))
print("cos:",np.cos(a))
print("log:",np.log(a))
print("tan:",np.tan(a))
print("Radian:",np.radians([180]))
print("Degree:",np.degrees([np.pi]))


exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
sqrt: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
log: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
tan: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
Radian: [3.14159265]
Degree: [180.]


In [70]:
# Binary operations

x=np.array([1,2,3,4])
y=np.array([3,4,5,7])
print("add:",np.add(x,y))
print("subtract:",np.subtract(x,y))
print("multiply:",np.multiply(x,y))
print("divide:",np.divide(x,y))
print("mod:",np.mod(x,y))
print("power:",np.power(x,y))
print("maximum:",np.maximum(x,y))
print("minimum:",np.minimum(x,y))


add: [ 4  6  8 11]
subtract: [-2 -2 -2 -3]
multiply: [ 3  8 15 28]
divide: [0.33333333 0.5        0.6        0.57142857]
mod: [1 2 3 4]
power: [    1    16   243 16384]
maximum: [3 4 5 7]
minimum: [1 2 3 4]


In [71]:
# Rounding Function

nums=np.array([1.2,2.4,3.8])
print("floor:",np.floor(nums))
print("ceil:",np.ceil(nums))
print("round:",np.round(nums))

floor: [1. 2. 3.]
ceil: [2. 3. 4.]
round: [1. 2. 4.]


In [72]:
# Aggregation Functions

data=np.array([20,30,40,50,60])
print("sum:",np.sum(data))
print("mean:",np.mean(data))
print("median:",np.median(data))
print("standard deviation:",np.std(data))
print("variance:",np.var(data))
print("Min:",np.min(data))
print("Max:",np.max(data))

sum: 200
mean: 40.0
median: 40.0
standard deviation: 14.142135623730951
variance: 200.0
Min: 20
Max: 60


In [73]:
# Agrregration along axix

matrix=np.array([[1,2,3],[4,5,6]])
print("Sum along axis 0:",np.sum(matrix,axis=0))
print("Sum along axis 1:",np.sum(matrix,axis=1))

Sum along axis 0: [5 7 9]
Sum along axis 1: [ 6 15]


In [74]:
# Using any() and all()

bool_arr=np.array([True,False,True])
print("Any True:",np.any(bool_arr))
print("All True:",np.all(bool_arr))

Any True: True
All True: False
